spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME} # aws 데이터베이스 주소
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    show-sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  elasticsearch:
    uris: ${ELASTICSEARCH_HOST}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
